// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Appointment
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public int ConsultantId { get; set; }

    public DateTime DateTime { get; set; }

    public string Status { get; set; }

    public string Note { get; set; }

    public virtual Consultant Consultant { get; set; }

    public virtual User User { get; set; }
}