// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class AssessmentResult
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public int AssessmentId { get; set; }

    public int Score { get; set; }

    public string RiskLevel { get; set; }

    public string Suggestion { get; set; }

    public DateTime? TakenAt { get; set; }

    public virtual Assessment Assessment { get; set; }

    public virtual User User { get; set; }
}