// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Repository.Models;

public partial class User
{
    public int Id { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string PasswordHash { get; set; }

    public DateOnly? DateOfBirth { get; set; }

    public string Gender { get; set; }

    public DateTime? CreatedAt { get; set; }

    public bool? IsActive { get; set; }

    public int? RoleId { get; set; }
    [JsonIgnore]

    public virtual ICollection<Appointment> Appointments { get; set; } = new List<Appointment>();
    [JsonIgnore]
    public virtual ICollection<AssessmentResult> AssessmentResults { get; set; } = new List<AssessmentResult>();
    [JsonIgnore]
    public virtual ICollection<BlogPost> BlogPosts { get; set; } = new List<BlogPost>();
    [JsonIgnore]
    public virtual Consultant Consultant { get; set; }
    [JsonIgnore]
    public virtual ICollection<Enrollment> Enrollments { get; set; } = new List<Enrollment>();
    [JsonIgnore]
    public virtual ICollection<Participation> Participations { get; set; } = new List<Participation>();
    [JsonIgnore]
    public virtual Role Role { get; set; }
}